from __future__ import annotations

import re

from openpyxl import load_workbook


_HEAT_RE = re.compile(r"^\s*Heat\s+(.+?)\s*$", re.IGNORECASE)


def _heat_numbers(value: object) -> list[int]:
    match = _HEAT_RE.match(str(value or ""))
    if not match:
        raise ValueError(f"Invalid Heat value {value!r}.")
    parts = [p.strip() for p in match.group(1).split("+")]
    if not parts or any(not p.isdigit() for p in parts):
        raise ValueError(f"Invalid Heat value {value!r}.")
    return sorted({int(p) for p in parts})


def parse_run_positions_excel(path_or_file) -> list[dict]:
    """Parse the workbook produced by ``build_run_positions_xlsx``."""
    wb = load_workbook(path_or_file, read_only=True, data_only=True)
    try:
        ws = wb["Run Positions"] if "Run Positions" in wb.sheetnames else wb.active
        rows = ws.iter_rows(values_only=True)
        headers = next(rows, None)
        expected = ["Heat", "Athlete Number", "Age Group", "Athlete Name", "Run Position"]
        if list(headers or [])[:5] != expected:
            raise ValueError("This is not a Run Position Export generated by Biathlon Event Manager.")
        mappings = []
        for row_number, row in enumerate(rows, start=2):
            if not any(value not in (None, "") for value in row[:5]):
                continue
            athlete_number = str(row[1] or "").strip()
            raw_position = row[4]
            if raw_position in (None, ""):
                position = None
            else:
                try:
                    position = int(raw_position)
                except (TypeError, ValueError) as exc:
                    raise ValueError(f"Invalid Run Position on row {row_number}.") from exc
            mappings.append({
                "athlete_number": athlete_number,
                "heat_numbers": _heat_numbers(row[0]),
                "run_position": position,
            })
        if not mappings:
            raise ValueError("The Run Position Export does not contain any mappings.")
        return mappings
    finally:
        wb.close()
